const de: BotsMessages = {
  roster: {
    search: 'Bots und Gruppenchats durchsuchen',
    searchPlaceholder: 'Bots und Gruppenchats durchsuchen…',
    newBotOrGroup: 'Neuer Bot oder Gruppenchat',
    groupChats: 'Gruppenchats',
    emptyTitle: 'Noch keine Bots',
    emptyDesc: 'Erstelle deinen ersten Bot.',
    noMatchQuery: query => `Keine Bots oder Gruppenchats passen zu „${query}“`,
    noMatchQueryOn: (query, gateway) => `Keine Bots oder Gruppenchats auf ${gateway} passen zu „${query}“`,
    noMatchFiltersOn: gateway => `Keine Bots oder Gruppenchats auf ${gateway} passen zu diesen Filtern`,
    noMatchFilters: 'Keine Bots oder Gruppenchats passen zu diesen Filtern.',
    clearFilters: 'Filter zurücksetzen',
    allHidden: 'Alle Bots sind ausgeblendet',
    allHiddenDesc: 'Sie arbeiten weiter und behalten ihren Verlauf.',
    showHidden: 'Ausgeblendete Bots zeigen',
    noHiddenMatch: 'Keine ausgeblendeten Bots passen zu diesen Filtern.',
    hiddenFromRoster: 'Aus der Liste ausgeblendet',
    pinned: 'Angeheftet',
    needsAttention: 'braucht Aufmerksamkeit',
    needsInput: 'Braucht deine Eingabe',
    botsAndGroups: 'Bots und Gruppenchats',
    botsOnly: 'Nur Bots',
    groupsOnly: 'Nur Gruppenchats',
    anyActivity: 'Beliebige Aktivität',
    activeNow: 'Gerade aktiv',
    recentlyActive: 'Kürzlich aktiv',
    older: 'Älter',
    gatewayRemoved: 'Gateway entfernt',
    onDemand: 'Auf Abruf',
    ready: 'Bereit',
    statusUnknown: 'Status unbekannt',
    unavailable: 'Nicht verfügbar',
    retryNow: 'Jetzt erneut versuchen',
    rosterUnavailable: reason =>
      `Liste nicht verfügbar: ${reason}. Wenn dein Gateway älter als profiles.list ist, aktualisiere Hermes und starte das Gateway neu.`,
    waitingForGateway:
      'Warte auf die Gateway-Verbindung… (entfernte Gateways brauchen manchmal ein paar Sekunden; wird automatisch wiederholt)'
  },
  sections: {
    newSection: 'Neuer Bereich',
    newTitle: 'Neuer Bereich',
    renameTitle: 'Bereich umbenennen',
    nameLabel: 'Bereichsname',
    namePlaceholder: 'z. B. Kunden',
    create: 'Erstellen',
    rename: 'Umbenennen…',
    moveUp: 'Nach oben',
    moveDown: 'Nach unten',
    unassigned: 'Ohne Bereich',
    options: name => `Optionen für den Bereich ${name}`,
    headingTip: 'Bots hierher ziehen · Doppelklick zum Umbenennen',
    emptyHint: 'Bots hierher ziehen',
    moveTo: 'In Bereich verschieben',
    newSectionEllipsis: 'Neuer Bereich…',
    removeFromSection: 'Aus dem Bereich entfernen',
    deleted: (name, count) =>
      count === 0
        ? `„${name}“ gelöscht`
        : `„${name}“ gelöscht — ${count} ${count === 1 ? 'Bot' : 'Bots'} nach „Ohne Bereich“ verschoben`,
    undo: 'Rückgängig'
  },
  bot: {
    newTitle: 'Neuer Bot',
    editTitle: 'Profil bearbeiten',
    editMenu: 'Bearbeiten…',
    helpPromptPlaceholder: 'Wobei soll dieser Bot helfen?',
    descriptionHint: 'Leer lassen, um sie aus Name und Beschreibung des Bots zu erzeugen.',
    newChatWith: 'Neue Unterhaltung mit diesem Bot',
    openBotChat: 'Bot-Chat öffnen',
    duplicate: 'Duplizieren',
    duplicateFailed: 'Duplizieren fehlgeschlagen',
    deleteTitle: 'Bot und Profil löschen?',
    removeFromAllGroups: 'Aus allen Gruppen entfernen',
    createFirstHint: 'Öffne den Bots-Bereich und klicke auf „Neuer Bot“.',
    createFailed: 'Das Profil konnte noch nicht erstellt werden',
    advanced: 'Erweitert',
    advancedHint: 'Erweitert — Modell, Skills, Toolsets, SOUL.md',
    advancedFailed: 'Erweiterte Konfiguration fehlgeschlagen',
    openAnotherChatUnsupported: 'Aktualisiere Hermes Desktop, um einen weiteren Bot-Chat zu öffnen.',
    remoteConnectionsUnsupported: 'Aktualisiere Hermes Desktop, um mit Bots auf anderen Verbindungen zu chatten.',
    chatEmpty: 'Schreib etwas, dann geht es los.',
    kickoff: 'Hey, erzähl mir von dir!'
  },
  avatar: {
    classicShapes: 'Klassische Formen',
    blobFromName: 'Blob-Gesicht — aus dem Namen des Bots gezeichnet',
    unlockFollowsName: 'Entsperren — das Gesicht folgt wieder dem Namen des Bots',
    randomize: 'Zufällig',
    tabBot: 'Bot',
    tabGenerate: 'Erzeugen',
    upload: 'Hochladen',
    tabPet: 'Tier',
    removeImage: 'Bild entfernen — Form verwenden',
    removeBackToShape: 'Entfernen — zurück zum Form-Avatar',
    describePlaceholder: 'Beschreibe deinen Avatar…',
    describeHint:
      'Leer lassen, um ihn aus Name, Titel und Beschreibung plus Agenten-Liste automatisch zu erzeugen.',
    matchTheName: 'Zum Namen passen',
    pickPet: 'Wähle ein Tier als Profilbild für diesen Bot.',
    petLoadFailed: 'Dieses Tier ließ sich nicht laden — nimm ein anderes.',
    imageTooLarge: 'Bild zu groß (höchstens 15 MB).',
    generationFailed: 'Avatar konnte nicht erzeugt werden',
    savedLocally: 'Aussehen lokal gespeichert; die Übertragung ist fehlgeschlagen',
    savedLocallyDescriptionFailed: 'Aussehen lokal gespeichert; die Beschreibung wurde nicht aktualisiert',
    generate: 'Erzeugen',
    generating: 'Wird erzeugt…'
  },
  group: {
    newTitle: 'Neuer Gruppenchat',
    manageDesc:
      'Ein Bot kann in mehreren Gruppenchats sein. Mitgliedschaften werden auf alle Geräte übertragen.',
    manageTitle: 'Gruppen verwalten',
    settingsTitle: 'Gruppeneinstellungen',
    settingsDesc:
      'Benenne die Gruppe um oder setze ein Raumbild. Mitglieder und Verlauf bleiben erhalten.',
    nameLabel: 'Gruppenname',
    searchToAdd: 'Bots zum Hinzufügen suchen',
    searchToAddPlaceholder: 'Bots zum Hinzufügen suchen…',
    removeFromSelection: 'Aus der Auswahl entfernen',
    disbandTitle: 'Gruppenchat auflösen?',
    deleteTitle: 'Gruppenchat löschen?',
    deleteAction: 'Löschen',
    composerPlaceholder: 'Schreib etwas — jeder Bot in dieser Gruppe hört mit.',
    attachHint: 'Dateien anhängen — jeder antwortende Bot sieht sie',
    newThread: 'Neuer Thread',
    reply: 'Antworten',
    replyInThread: 'Im Thread antworten',
    replyInThreadPlaceholder: 'Im Thread antworten…',
    openThread: 'Diesen Thread öffnen',
    collapseThread: 'Thread einklappen',
    collapseThreadLabel: 'Diesen Thread einklappen',
    activity: 'Aktivität',
    noActivityYet: 'In dieser Runde ist noch nichts passiert.',
    showActivity: 'Raum-Aktivität zeigen',
    hideActivity: 'Raum-Aktivität ausblenden',
    stop: 'Stopp',
    stopHint: 'Diesen Lauf stoppen — unterbricht den Bot, der dran ist, und hält die übrigen an',
    allHeldStatus: count => `Alle ${count} Bots sind angehalten`,
    heldMembersStatus: members => `Angehalten: ${members}`,
    holdReleaseHint: 'Erwähne einen angehaltenen Bot oder schicke @all resume, um sie freizugeben.',
    needsYourInput: 'Ein Bot in diesem Gruppenchat braucht deine Eingabe',
    pictureGenerationFailed: 'Gruppenbild konnte nicht erzeugt werden',
    nameTaken: name => `Eine Gruppe namens „${name}“ gibt es schon.`,
    memberCount: count => `${count} Bots`,
    settingsHint: group => `Gruppeneinstellungen — ${group} umbenennen oder ein Raumbild setzen`,
    settingsLabel: group => `Gruppeneinstellungen für ${group}`,
    disbandHint: group => `Den Gruppenchat ${group} auflösen`,
    disbandLabel: group => `${group} auflösen`,
    disbandAction: 'Auflösen',
    disbanding: 'Wird aufgelöst…',
    disbandDone: 'Aufgelöst',
    disbanded: group => `„${group}“ aufgelöst`,
    disbandDescPrefix: 'Das entfernt die Gruppierung ',
    disbandDescSuffix: count =>
      ` von ihren ${count} Bots und leert das gemeinsame Raumprotokoll. Die Bots selbst und ihre Sitzungen je Gruppe bleiben erhalten.`,
    stopped: group => `${group} gestoppt — die übrigen Runden warten, bis du fortsetzt`,
    removeAttachment: 'Anhang entfernen',
    threadFallback: 'Thread',
    replyCount: replies => `${replies} ${replies === 1 ? 'Antwort' : 'Antworten'}`,
    dropToThread: 'Hier ablegen, um es an diese Thread-Antwort zu hängen',
    dropToRoom: 'Hier ablegen — jeder antwortende Bot sieht es',
    waitingForAnswer: 'Warte auf deine Antwort…',
    memberThinking: name => `${name} denkt nach…`,
    roomWorking: 'Der Raum arbeitet…',
    messageRoom: group => `Nachricht an ${group}`,
    newThreadPlaceholder: group => `Neuer Thread in ${group}… (@name für einzeln, @everyone für alle)`,
    everyoneMeta: 'Jeder Bot im Raum',
    commandApproval: 'Befehlsfreigabe',
    answerFailed: (handle, error) => `Die Antwort an @${handle} ging nicht raus: ${error}`,
    wantsToRunCommand: handle => `@${handle} möchte einen Befehl ausführen:`,
    asks: handle => `@${handle} fragt:`,
    answerTo: member => `@${member} antworten`
  },
  tools: {
    skillsHub: 'Hermes Skills Hub',
    filterSkills: 'Skills filtern…',
    searchHub: 'Im Hub suchen (Community und bekannte Quellen)…',
    noMcpServers: 'Keine MCP-Server eingerichtet oder im Katalog.'
  },
  cron: {
    filterHint:
      'In diesem Profil gibt es Zeitpläne, aber keiner ist diesem Bot zugeordnet. Nenne einen Zeitplan „[bot:<name>] …“, damit er hier auftaucht, oder sieh sie unten unter Cron.',
    needsRosterFirst: 'Dieser Bot muss zuerst in der Liste erscheinen.',
    staleNotice: 'Die Zeitpläne ließen sich nicht neu laden. Angezeigt wird die zuletzt bekannte Liste.',
    readFailure: 'Die Liste ist vermutlich noch da — das war ein Lesefehler, kein Löschen.',
    createDesc: bot =>
      `Eine wiederkehrende Aufgabe, die ${bot} nach Zeitplan ausführt. Die Läufe landen im eigenen Chatverlauf.`,
    instruction: 'Anweisung',
    whenToRun: 'Wann ausführen',
    dayOfMonth: 'Tag im Monat',
    sendResultsTo: 'Ergebnisse senden an',
    runHistoryOnly: 'Nur in den Verlauf',
    botChatTarget: bot => `Chat von ${bot} (der Bot antwortet)`,
    continuity:
      'Kontinuität: Jeder Lauf sieht die Ausgabe des vorherigen (Doppeltes vermeiden, dort weitermachen, wo er aufgehört hat)',
    onceIn: when => `Einmalig (${when})`,
    everyNDays: days => `Alle ${days} Tage`,
    everyNHours: hours => `Alle ${hours} h`,
    everyNMinutes: minutes => `Alle ${minutes} min`,
    freqOnce: 'Einmalig, in…',
    freqHourly: 'Jede Stunde',
    freqDaily: 'Jeden Tag',
    freqWeekdays: 'Werktags',
    freqWeekly: 'Jede Woche',
    freqMonthly: 'Jeden Monat',
    freqInterval: 'Intervall',
    freqAdvanced: 'Erweitert…',
    unitMinutes: 'Minute(n)',
    unitHours: 'Stunde(n)',
    unitDays: 'Tag(e)',
    runsOnce: (count, unit) => `Läuft einmal, in ${count} ${unit}`,
    runsHourly: 'Läuft zu jeder vollen Stunde',
    runsDaily: time => `Läuft jeden Tag um ${time}`,
    runsWeekdays: time => `Läuft Montag bis Freitag um ${time}`,
    runsWeekly: (day, time) => `Läuft jeden ${day} um ${time}`,
    runsMonthly: (day, time) => `Läuft am ${day}. jedes Monats um ${time}`,
    runsInterval: (count, unit) => `Läuft alle ${count} ${unit}`,
    runsRaw: 'Roher Zeitplan — jeweils Nm/Nh/Nd oder ein Cron-Ausdruck mit 5 Feldern',
    timesTotal: count => `, insgesamt ${count} Mal`
  }
}
